// lib/states.js
module.exports = {
  ABI: "Abia",
  ADA: "Adamawa",
  AKW: "Akwa Ibom",
  ANA: "Anambra",
  BAU: "Bauchi",
  BAY: "Bayelsa",
  BEN: "Benue",
  BOR: "Borno",
  CRR: "Cross River",
  DEL: "Delta",
  EBO: "Ebonyi",
  EDO: "Edo",
  EKI: "Ekiti",
  ENU: "Enugu",
  GOM: "Gombe",
  IMO: "Imo",
  JIG: "Jigawa",
  KAD: "Kaduna",
  KAN: "Kano",
  KAT: "Katsina",
  KEB: "Kebbi",
  KOG: "Kogi",
  KWA: "Kwara",
  LAG: "Lagos",
  NAS: "Nasarawa",
  NIG: "Niger",
  OGU: "Ogun",
  OND: "Ondo",
  OSU: "Osun",
  OYO: "Oyo",
  PLA: "Plateau",
  RIV: "Rivers",
  SOK: "Sokoto",
  TAR: "Taraba",
  YOB: "Yobe",
  ZAM: "Zamfara"
};
